### ISSUE TITLE
添加模糊音设置

### ISSUE THREAD

**Issue by mizhewei** [LufsX/rime#10]
1. hsu -> shu 这一类 sh ch zh 键盘有时候有延迟
2. 南方人有的 feng fong误用

不知道怎么添加规则，大佬帮帮忙

**Comment by LufsX** [comment]
1. hsu -> shu 这种嘛，加条规则就行
`- derive/([csz])h/h$1/ # hc、hs、hz => ch、sh、zh`

2. fong -> feng 这类误用加这个规则
`- derive/^([bpmfw])eng$/$1ong/ # bpmfw 后接 ong => bpmfw 后接 eng`

现在配置已经支持，hsu -> shu 这类错误纠正默认开启，feng fong 这类需自己解除输入方案内 `其它模糊音` 对应的注释即可
