### ISSUE TITLE
搜狗个人词库导入

### ISSUE THREAD

**Issue by mizhewei** [LufsX/rime#11]
我想问一下为什么搜狗导出的个人词库不管怎么样都没办法添加成功

步骤：
从win端的搜狗同步后导出词库 通过深蓝转换成txt
将已经有的词典文件副本，然后把txt内容复制进去 修改文件名
然后在extended文件里面加上词库名 然后重新部署 
<img width="542" alt="图片" src="https://user-images.githubusercontent.com/38462600/216993921-befc6622-59df-45fe-bd15-dfd24da99b8b.png">
<img width="372" alt="图片" src="https://user-images.githubusercontent.com/38462600/216994489-b432f019-bac5-4735-b0f6-c2c1174a9332.png">

输入这里面的词汇 例如zuoyoudianfei 左右电费 还是没有出现，如图
<img width="363" alt="图片" src="https://user-images.githubusercontent.com/38462600/216994952-555d4ee2-802e-46b9-962d-c223353f80a0.png">

我是有哪一步做错了吗？ 还是不可以用这个方法导入 有相关的教程吗 谢谢

**Comment by mizhewei** [comment]
找到问题了 分词没有用tab
无语 复制编辑千万不要用sublime，根本看不出来 请一定要用vscode

**Comment by LufsX** [comment]
> 找到问题了 分词没有用tab 无语 复制编辑千万不要用sublime，根本看不出来 请一定要用vscode

啊这，建议 VS CODE 保平安 🤣
