### ISSUE TITLE
macos下emoji不显示

### ISSUE THREAD

**Issue by aoxiangfly** [LufsX/rime#14]
macos 13， 将配置文件下载下来，部署以后，输入示例中的嘿嘿，不显示emoji。输入其它的词语，也没有任何emoji图片候选

**Comment by LufsX** [comment]
鼠须管保存 emoji 状态有些问题，就默认关闭了，需要手动通过 F2 来切换 emoji 开启

也可以将[这一行](https://github.com/LufsX/rime/blob/master/lufs_flypy.schema.yaml#L25)取消注释，来达到默认开启的效果

**Comment by aoxiangfly** [comment]
好的，感谢，已经可以了
