### ISSUE TITLE
关于开启繁简转换

### ISSUE THREAD

**Issue by kevinyjliang** [LufsX/rime#16]
你好, 尝试在 `lufs_pinyin.schema.yaml` 中添加配置:
![image](https://user-images.githubusercontent.com/35890564/229679551-1bfb016a-ef94-493c-bb59-17c3744b78f3.png)
却无法生效, 请问是什么原因呢?

**Comment by LufsX** [comment]
参见 https://github.com/LufsX/rime/issues/12#issuecomment-1429458323

**Comment by LufsX** [comment]
配置已内置～
