### ISSUE TITLE
导入后无法输入中文

### ISSUE THREAD

**Issue by Libyte** [LufsX/rime#17]
我在按照教程导入后，切换到鼠须管输入时无法切换成中文输入发

**Comment by Libyte** [comment]
修改配置文件切换后也不能使用中文输入法，但是可以与系统输入发进行切换

**Comment by LufsX** [comment]
<img width="827" alt="image" src="https://user-images.githubusercontent.com/33221883/232064606-d8c8ca05-ea3d-4aa5-a74c-49b7dd4ff49e.png">

尝试开启这个选项，稍候我修一下这个问题

（这个选项一直开着没关过，关了的情况没测 🤣

**Comment by LufsX** [comment]
其实是邮件通知啦（

**Comment by Libyte** [comment]
这个选项我一直是开着的，但是还是不能输入中文（悲

**Comment by LufsX** [comment]
那就奇怪了，我配置默认是是剔除了英文输入的，重新部署也没用嘛？鼠须管版本是？有日志嘛？

**Comment by Libyte** [comment]
用的是0.16.0，日志文件我不太清楚在哪里

**Comment by LufsX** [comment]
麻烦打开用户设定文件夹看看目录结构，猜测可能是配置文件没装对

**Comment by Libyte** [comment]
还是不行

**Comment by LufsX** [comment]
那就奇怪了，没遇到过这种问题（

官方的最新版本是 [0.16.2](https://github.com/rime/squirrel/releases/download/0.16.2/Squirrel-0.16.2.zip)，安装完后应该会叫要求退出登录

日志文件在 目录 $TMPDIR/rime.squirrel.INFO 下（可以在终端中使用 `open $TMPDIR` 打开文件夹，找到对应文件即可）

**Comment by Libyte** [comment]
<img width="811" alt="image" src="https://user-images.githubusercontent.com/55917124/232090783-5574e30b-c335-4d6f-b83f-80d8d2091152.png">
这个我也试过了，但还是不行

**Comment by Libyte** [comment]
<img width="682" alt="image" src="https://user-images.githubusercontent.com/55917124/232095264-4a8cf257-f5f0-45c6-bc81-d1d900cae15b.png">
我找了一下，error应该就是这一部分

**Comment by Libyte** [comment]
我靠，老哥我弄好了，我看日誌裏面說，找不到default.custom.yaml文件，項目里命名是default.yaml，修改一下就好了

**Comment by Libyte** [comment]
还想问一下老哥，如何设置输入全是简体字呢，我输入的时候也有繁体字还是会蹦出来，但是我找不到设置哪个选项

**Comment by LufsX** [comment]
怪，默认设置的就是全简体输出，按理说 `default.yaml` 也不需要改名，真的怪，难不成有优先级更高的配置？🤔

切简繁体的话按 `F2`（可能需要同时按住 `Fn`），进去找选单就行

**Comment by Libyte** [comment]
f2之後我就不會按了，回車嗎還是別的

**Comment by Libyte** [comment]
而且好像不止這一個文件命名需要改

**Comment by LufsX** [comment]
空格 或是 数字，选中你要更改的东西就行

**Comment by Libyte** [comment]
而且現在不是F2，而是crtl+`

**Comment by Libyte** [comment]
改了，但還是會出繁體字

**Comment by LufsX** [comment]
https://github.com/LufsX/squirrel/actions/runs/4141388830

试试这里的鼠须管，我自己系统是 macOS Ventura 13.3.1，鼠须管版本是 0.16.2

**Comment by Libyte** [comment]
系統版本與軟件版本都一致的

**Comment by Libyte** [comment]
候选词固定是五个，设置修改不了，老歌晚安，我熬不动了，先撤了

**Comment by LufsX** [comment]
> 不过现在可以进行设置修改一些东西了，老哥后续会开发随系统修改皮肤的功能吗

这个要看 鼠须管 那边的功能，凑巧的是，已经有随着夜间模式切换主题的功能了

**Comment by LufsX** [comment]
https://github.com/LufsX/rime/commit/f669f545c4da1ebeb1a8358d1c629e8d31ede376

已经定位到问题了，临时回退了，现在应该就可以正常使用惹

**Comment by Libyte** [comment]
ok，老哥辛苦，明早我弄一下

**Comment by Libyte** [comment]
老哥早上我试了一下可以正常使用了，感谢老哥，等出主题切换@我一下，感谢感谢
