### ISSUE TITLE
无法自动造词和记忆词频

### ISSUE THREAD

**Issue by ThreeIce** [LufsX/rime#19]
RT
使用Trime  3.2.1

**Comment by LufsX** [comment]
记忆词频，需要一定的次数，毕竟词库哪边是带权重的
自动造词同理，还有长句模型的影响，需要将整个词的输入到一定程度才能造词

不过也有可能是 Trime 的问题，但我 Android 上没用 Trime（最近没啥时间测试，有时间再看看 😂

**Comment by ThreeIce** [comment]
该问题更新到新版后已解决。
（新版同文问题多的要死，要命

**Comment by ThreeIce** [comment]
补充解决方案：若使用3.2.1, 可以将userdb文件夹删除后重部署，而后词频记忆会恢复
