### ISSUE TITLE
请问能不能增加一下，状态图标更新这个。。。

### ISSUE THREAD

**Issue by nevertoday** [LufsX/rime#2]
double_pinyin_flypy 
设置成这个的时候可以有，当前输入法状态跟随，比如是英文，会提示：A
是中文会提示：中

**Comment by LufsX** [comment]
方案是将英文输入交给系统输入法处理的说，从方案上就已经剔除英文输入了（

等有时间后我再详细写写如何添加哈~

**Comment by LufsX** [comment]
你的这个需求应该能被 [Input Source Pro](https://inputsource.pro) 很好的解决，鼠须管的中英文提示只有你切换的时候才会显示当前状态，这个可以持续的提示当前正在用什么输入法 

---

如果想要把鼠须管的英文输入功能加回来，可以参考 #5 ，操作步骤都是一样的
