### ISSUE TITLE
单字偶然不全

### ISSUE THREAD

**Issue by ThreeIce** [LufsX/rime#20]
如输入键角时，单输入键和角可以找到对应字，输入jmjn，先选键后再要找“角”，找不到
使用Trime 3.2.1

**Comment by ThreeIce** [comment]
目前在Trime 3.2.10上再次测试，问题仍然存在

**Comment by ThreeIce** [comment]
经测试（灵光一闪），把emoji提示关闭后恢复正常，开启后又存在，推测与emoji有关

**Comment by LufsX** [comment]
测试无此问题
版本 v3.2.10-0-g6098ec72-release

![Screenshot_20230425-132753](https://user-images.githubusercontent.com/33221883/234182464-134bfe38-d1fe-4abb-989c-991e3926bafa.png)

**Comment by ThreeIce** [comment]
容我周末做个详细配置文件比对和情况复现再做答复

**Comment by ThreeIce** [comment]
问题已锁定：在特定配置下，将候选栏词数改为5以上，trime会吞词（固定吞每页多余的）
