### ISSUE TITLE
需求粘贴板功能

### ISSUE THREAD

**Issue by WeichangChen2020** [LufsX/rime#23]
大佬有没有希望能添加粘贴板的功能？windows下面有win+v能用，mac没有粘贴板很不方便。

**Comment by LufsX** [comment]
这个鼠须管不太好处理，个人建议用专门的剪贴板管理工具

个人用的是 Raycast 自带的剪贴板管理~

支持支持图片文件链接等类型，挺好用的，推荐一下

**Comment by WeichangChen2020** [comment]
好的谢谢，我去试试
