### ISSUE TITLE
拼音输入法的支持程度

### ISSUE THREAD

**Issue by Lzy49** [LufsX/rime#25]
想问下输入法的词库

**Comment by LufsX** [comment]
用了 https://github.com/iDvel/rime-ice 的基础词表和 emoji
用了清华带词频的部分词库 https://github.com/thunlp/THUOCL
然后加了些搜狗输入法转化来的词库

其中，有词频的是基础词表换清华的词库，可以自行替换喜欢的词库（词频方面一般用用就会好些了，没有找到更好的词库词频，要大要多的话可以尝试一下 https://github.com/iDvel/rime-ice 的大词库
