### ISSUE TITLE
emoji不显示

### ISSUE THREAD

**Issue by Truman-NB** [LufsX/rime#30]
<img width="912" alt="Screen Shot 2023-12-17 at 4 08 19 PM" src="https://github.com/LufsX/rime/assets/76169229/d24fc245-473d-4ab8-ad4f-47292fe85868">
你好，我这个配置感觉没问题啊，而且f4设置也选择emoji开启，opencc里也有emoji文件，但是就是打不出来emoji，是怎么回事呢？

**Comment by LufsX** [comment]
检查下 opencc 下的 emoji.json 指向的文件是否存在

**Comment by Truman-NB** [comment]
有的 指的是emoji_word.txt

**Comment by LufsX** [comment]
> 有的 指的是emoji_word.txt

哪重新部署后尝试输入 emoji_word.txt 内的词组，看看 emoji 是否正常显示

![image](https://github.com/LufsX/rime/assets/33221883/69bf2016-d5a1-4d08-a475-3af2fd34220a)
![image](https://github.com/LufsX/rime/assets/33221883/4aed21da-6eec-41b0-af2c-ccccf57a6d1e)

**Comment by Truman-NB** [comment]
<img width="479" alt="Screen Shot 2023-12-19 at 1 50 59 PM" src="https://github.com/LufsX/rime/assets/76169229/071833e7-c901-4603-8f5d-a4f4ad189500">

<img width="208" alt="Screen Shot 2023-12-19 at 1 51 32 PM" src="https://github.com/LufsX/rime/assets/76169229/c96f1d90-99d7-41c2-8ced-021c4aa65b78">
还是没有

**Comment by LufsX** [comment]
> <img alt="Screen Shot 2023-12-19 at 1 50 59 PM" width="479" src="https://private-user-images.githubusercontent.com/76169229/291488431-071833e7-c901-4603-8f5d-a4f4ad189500.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NjcwOTIsIm5iZiI6MTcwMjk2Njc5MiwicGF0aCI6Ii83NjE2OTIyOS8yOTE0ODg0MzEtMDcxODMzZTctYzkwMS00NjAzLThmNWQtYTRmNGFkMTg5NTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA2MTk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5OWNmMTkwMTc3NTA0OGY5ZjRmOTA0NzI5MDQ2NzQ0ZWE3Yzg1NGMyOWViNDRiMDljNjMxMmI4NjRiMzNhN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cNSehTTIe4acqTH7DZrRn5GuhH511vEMpHvSq6Tw7bw"> <img alt="Screen Shot 2023-12-19 at 1 51 32 PM" width="208" src="https://private-user-images.githubusercontent.com/76169229/291488532-c96f1d90-99d7-41c2-8ced-021c4aa65b78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NjcwOTIsIm5iZiI6MTcwMjk2Njc5MiwicGF0aCI6Ii83NjE2OTIyOS8yOTE0ODg1MzItYzk2ZjFkOTAtOTlkNy00MWMyLThjZWQtMDIxYzRhYTY1Yjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA2MTk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiZDFlMWQ2ODYyOTEzZDgyZWU1NDIyNGJjYWQ2NWZmY2I3YzUzNGI2MmJlMmY1MmYwZGM3NDVmNGViZDY5NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LHQPKMq-wNtDgV8rEwAmAnDnzPsc7zF-4Sa0x9TIo1Q"> 还是没有

那就奇怪了🤔

是不是 patch 没打上？检查下 /build/ 下方案打完 patch 的配置文件中有没有对应字段

**Comment by Truman-NB** [comment]
这个我也检查过 里面也有😂
<img width="912" alt="Screen Shot 2023-12-19 at 6 35 23 PM" src="https://github.com/LufsX/rime/assets/76169229/7a298702-75cc-4fb4-9450-616131997c44">

**Comment by Truman-NB** [comment]
而且这个鼠须管的根据特定app指定默认中英文的功能也不是很好使，触发不是很灵敏，如果把苹果的字典加进去默认英文，皮肤会变成默认的，感觉就是软件bug。

**Comment by LufsX** [comment]
> 这个我也检查过 里面也有😂 <img alt="Screen Shot 2023-12-19 at 6 35 23 PM" width="912" src="https://private-user-images.githubusercontent.com/76169229/291559170-7a298702-75cc-4fb4-9450-616131997c44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODQ1NDcsIm5iZiI6MTcwMjk4NDI0NywicGF0aCI6Ii83NjE2OTIyOS8yOTE1NTkxNzAtN2EyOTg3MDItNzVjYy00ZmI0LTk0NTAtNjE2MTMxOTk3YzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDExMTA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYmFjYjljZjc1MzU4ODA3ZWU3NmUxMGY0YWU1NGJkMjYwMmNlMDZmN2ViNzg0ZjA5MDRjMDAwYmZiMzNjYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lix8RIMUhVGPC4KFPHQ1M_6vAfc_reH19mqBW6lXPSY">

那就奇怪了，我自己的配置都是正常的，你按[这里的方法](https://github.com/rime/rime-emoji)安装下试试

> 而且这个鼠须管的根据特定app指定默认中英文的功能也不是很好使，触发不是很灵敏，如果把苹果的字典加进去默认英文，皮肤会变成默认的，感觉就是软件bug。

是的，所以我自己的配置是直接剔除了鼠须管的英文输入的，配合 [Input Source Pro](https://inputsource.pro/zh-CN) 使用，体验极佳

**Comment by Truman-NB** [comment]
我也照他的自助安装试了，也是没用，算了。
我也试试那个，是需要原生输入法吗，还是可以直接切换鼠须管的中英文

**Comment by LufsX** [comment]
> 我也照他的自助安装试了，也是没用，算了。 我也试试那个，是需要原生输入法吗，还是可以直接切换鼠须管的中英文

对，英文输入使用的是系统的 ABC 输入法，中文输入是鼠须管
<img width="264" alt="image" src="https://github.com/LufsX/rime/assets/33221883/9e4b7836-1fce-42d7-b8a3-e1f922452c89">

然后再使用 Input Source Pro 给每个应用/网页设置不同的输入法

<img width="892" alt="image" src="https://github.com/LufsX/rime/assets/33221883/4956af41-bad5-45a8-bdb9-68e06d97cee4">

**Comment by Truman-NB** [comment]
好的，感谢！
