### ISSUE TITLE
emoji词库似乎不正确？

### ISSUE THREAD

**Issue by Ollif** [LufsX/rime#32]
打开dicts/emoji.dict.yaml确认内容与https://github.com/iDvel/rime-ice/blob/main/opencc/emoji.txt不一致。

**Comment by LufsX** [comment]
本方案没有中英混输，故文件 emoji 文件剔除了英文

方案的词库也不大，主要靠自己养，但这样某些词组不在 emoji 输入里，不太方便

所以就把 [opencc/emoji_word.txt](https://github.com/LufsX/rime/blob/master/opencc/emoji_word.txt) 抽出来单独组了这个[词库](https://github.com/LufsX/rime/blob/master/dicts/emoji.dict.yaml)
