### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by Carrotist** [LufsX/rime#33]
系统：Windows11
软件：小狼毫0.15.0.0（最新版）
我在使用您的配置时，按 shift+R 进行中英文转换会导致转换时自动出现一个大写 R ，因为默认输入大写英文时本身也可以使用shift+字母的方法，这使我感到相当不方便，请问有没有办法可以改为微软拼音默认的按shift转换中英文？
另外，请问我不习惯4候选词，想手动增加候选词应该去哪里设置？
祝生活愉快！
![image](https://github.com/LufsX/rime/assets/102582016/bde7719a-df60-47ca-844d-83e0ed8e1435)

**Comment by LufsX** [comment]
应该是需要左 shift 切换中英文输入吧

把该行的 `noop` 改为 `commit_code`，这样比较贴合原生输入法的体验（可参见[定制指南](https://blog.isteed.cc/post/squirrel-customization-2022/#%E5%85%A8%E5%B1%80%E8%AE%BE%E7%BD%AE)

https://github.com/LufsX/rime/blob/3a4840936c10837221f70f6deb01dd641bd95eff/default.yaml#L51

----

候选词的话，更改这行的值即可（也可参见[定制指南](https://blog.isteed.cc/post/squirrel-customization-2022/#%E5%85%A8%E5%B1%80%E8%AE%BE%E7%BD%AE)

https://github.com/LufsX/rime/blob/3a4840936c10837221f70f6deb01dd641bd95eff/default.yaml#L27

**Comment by Carrotist** [comment]
谢谢您
