### ISSUE TITLE
关于小狼毫配置emoji输入中英混输的问题。

### ISSUE THREAD

**Issue by Bluecat003** [LufsX/rime#34]
我是用了作者的自用配置，但是没法输入emoji表情。还有就是有办法实现中英混输吗？
![代码片段](https://github.com/LufsX/rime/assets/72208289/a7008208-d1d5-49bf-800c-b52a339ef38c)

**Comment by LufsX** [comment]
Emoji 输入默认关闭，可以通过 F2 在对应的选单里开启（F2，空格，下一页，按 `2` 切换状态）

![image](https://github.com/LufsX/rime/assets/33221883/58c5551e-ba6e-43ff-a6c2-2b989f3ccf09)

---

中英混输维护成本太高了，我自己加了点常用词语到[用户自定义字典](https://github.com/LufsX/rime/blob/melt-eng/custom_phrase.txt)里，如果需要，可以看看本仓库的 [melt-eng 分支](https://github.com/LufsX/rime/tree/melt-eng)

**Comment by Bluecat003** [comment]
![image](https://github.com/LufsX/rime/assets/72208289/597df962-60b1-4729-a379-2fbdcd004d89)
符号里面可以打出来一些，但是按照你上面的方法还是没有，比如输入「大笑」、「笑」之类的都没有Emoji显示
![image](https://github.com/LufsX/rime/assets/72208289/2fece7e7-e633-43cc-afb3-887471d6e88c)

**Comment by LufsX** [comment]
> ![image](https://private-user-images.githubusercontent.com/72208289/316708592-597df962-60b1-4729-a379-2fbdcd004d89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0Mjg4OTUsIm5iZiI6MTcxMTQyODU5NSwicGF0aCI6Ii83MjIwODI4OS8zMTY3MDg1OTItNTk3ZGY5NjItNjBiMS00NzI5LWEzNzktMmZiZGNkMDA0ZDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA0NDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NjA4MjYxNGIyY2U1NWI2MmM4OTE4ZTU0MjYwY2IwNTkwYThhNmI0ZjdmNzU4NWZjMmFiZDJlNGVjOTI4ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z8eyvd-XIAxddEDYJwYWa5rwxEVhNCURFf4kphatf2s) 符号里面可以打出来一些，但是按照你上面的方法还是没有，比如输入「大笑」、「笑」之类的都没有Emoji显示 ![image](https://private-user-images.githubusercontent.com/72208289/316708703-2fece7e7-e633-43cc-afb3-887471d6e88c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0Mjg4OTUsIm5iZiI6MTcxMTQyODU5NSwicGF0aCI6Ii83MjIwODI4OS8zMTY3MDg3MDMtMmZlY2U3ZTctZTYzMy00M2NjLWFmYjMtODg3NDcxZDZlODhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA0NDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlY2E1Y2ZiNWZmMTdjNTU4NjBiMzQxZmRiNmJjMWY3YmY2ZmUyMDQwNzlhOWY0ZWZmMjBhOWVjMDI5YmJiNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WXLAmtWYZEMnhmprVVD8386a1zo3Qv_qUnJAlHMCOgY)

检查下配置文件是否完整（emoji 依赖 `opencc` 目录下的文件）

我用的是 [CI 版](https://github.com/rime/weasel/releases/tag/latest)的小狼毫，配置一直在用，emoji 是没问题的

![image](https://github.com/LufsX/rime/assets/33221883/0a5e6e45-1ae8-41a6-baaf-044e0fbb3a44)
