### ISSUE TITLE
大佬，请增加reimu主题

### ISSUE THREAD

**Issue by spiljj** [LufsX/rime#38]
候选字阴影效果非常好看，但好像没找到如何设置的。谢谢🥳

**Comment by LufsX** [comment]
如果是想为 Windows 的小狼毫增加主题，那么很遗憾，阴影效果无法实现，小狼毫无法控制高亮选项阴影

Windows 下暂且只能通过手调配色实现这种效果

![image](https://github.com/user-attachments/assets/44ef3fe6-eb4a-4d6b-a04d-01357a5e52a0)

---

鼠须管仅需单独设置以下 shadow_size 即可，小狼毫暂时没有找到这个选项

https://github.com/LufsX/rime/blob/5d4f507d8debf7c028140f32975a2322bab1ba06/squirrel.yaml#L151

**Comment by spiljj** [comment]
> 如果是想为 Windows 的小狼毫增加主题，那么很遗憾，阴影效果无法实现，小狼毫无法控制高亮选项阴影
> 
> Windows 下暂且只能通过手调配色实现这种效果
> 
> ![image](https://private-user-images.githubusercontent.com/33221883/395884825-44ef3fe6-eb4a-4d6b-a04d-01357a5e52a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzE3NzUsIm5iZiI6MTczNDMzMTQ3NSwicGF0aCI6Ii8zMzIyMTg4My8zOTU4ODQ4MjUtNDRlZjNmZTYtZWI0YS00ZDZiLWEwNGQtMDEzNTdhNWU1MmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA2NDQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YmU4NzMwOWI0NGMzMWQxNzg4NTBhOTljMjVkZWUzMTFhZDlmMGUzOWJlYjhkMjc2NWRiNzgyOTQ0MzgzYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.So93Z5KhOd_qXRLt_TOTXVLASbApn1SkeYdmZIwgzu0)
> 
> 鼠须管仅需单独设置以下 shadow_size 即可，小狼毫暂时没有找到这个选项
> 
> https://github.com/LufsX/rime/blob/5d4f507d8debf7c028140f32975a2322bab1ba06/squirrel.yaml#L151
<img width="96" alt="截屏2024-12-16 下午2 45 17" src="https://github.com/user-attachments/assets/225dfde6-0a52-4ea9-9e84-c53b04c3bfd2" />

感谢作者，已经配制好了，谢谢
